apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
  name: diracx-cms-cleanup-authdb
  namespace: default
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata: {}
    spec:
      template:
        metadata: {}
        spec:
          containers:
          - args:
            - /bin/bash
            - /scripts/cleanup-authdb
            command:
            - /bin/bash
            - /entrypoint.sh
            envFrom:
            - secretRef:
                name: diracx-secrets
            - secretRef:
                name: diracx-sql-connection-urls
            - secretRef:
                name: diracx-dynamic-secrets
            image: ghcr.io/diracgrid/diracx/services:v0.0.13
            imagePullPolicy: Always
            name: diracx-cleanup
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /entrypoint.sh
              name: container-entrypoint
              subPath: entrypoint.sh
            - mountPath: /diracx_source
              name: diracx-code-mount
              readOnly: true
            - mountPath: /diracx_source/diracx/diracx-api/src/diracx_api.egg-info
              name: diracx-api-editable-install
            - mountPath: /diracx_source/diracx/diracx-tasks/src/diracx_tasks.egg-info
              name: diracx-tasks-editable-install
            - mountPath: /diracx_source/diracx/diracx-client/src/diracx_client.egg-info
              name: diracx-client-editable-install
            - mountPath: /diracx_source/diracx/diracx-db/src/diracx_db.egg-info
              name: diracx-db-editable-install
            - mountPath: /diracx_source/diracx/diracx-testing/src/diracx_testing.egg-info
              name: diracx-testing-editable-install
            - mountPath: /diracx_source/diracx/diracx-logic/src/diracx_logic.egg-info
              name: diracx-logic-editable-install
            - mountPath: /diracx_source/diracx/diracx-core/src/diracx_core.egg-info
              name: diracx-core-editable-install
            - mountPath: /diracx_source/diracx/diracx-cli/src/diracx_cli.egg-info
              name: diracx-cli-editable-install
            - mountPath: /diracx_source/diracx/diracx-routers/src/diracx_routers.egg-info
              name: diracx-routers-editable-install
            - mountPath: /keystore/jwks.json
              name: keystore
              subPath: jwks.json
            - mountPath: /scripts
              name: scripts
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
          - name: keystore
            secret:
              defaultMode: 420
              items:
              - key: jwks.json
                path: jwks.json
              secretName: diracx-jwks
          - configMap:
              defaultMode: 420
              name: diracx-cms-cleanup-authdb
            name: scripts
          - name: diracx-code-mount
            persistentVolumeClaim:
              claimName: pvc-diracx-code
          - emptyDir:
              sizeLimit: 5Mi
            name: diracx-api-editable-install
          - emptyDir:
              sizeLimit: 5Mi
            name: diracx-tasks-editable-install
          - emptyDir:
              sizeLimit: 5Mi
            name: diracx-client-editable-install
          - emptyDir:
              sizeLimit: 5Mi
            name: diracx-db-editable-install
          - emptyDir:
              sizeLimit: 5Mi
            name: diracx-testing-editable-install
          - emptyDir:
              sizeLimit: 5Mi
            name: diracx-logic-editable-install
          - emptyDir:
              sizeLimit: 5Mi
            name: diracx-core-editable-install
          - emptyDir:
              sizeLimit: 5Mi
            name: diracx-cli-editable-install
          - emptyDir:
              sizeLimit: 5Mi
            name: diracx-routers-editable-install
          - configMap:
              defaultMode: 420
              name: diracx-container-entrypoint
            name: container-entrypoint
  schedule: 0 0 1 * *
  successfulJobsHistoryLimit: 3
  suspend: false
