apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: diracx-cms
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: diracx
    app.kubernetes.io/version: v0.0.13
    helm.sh/chart: diracx-1.0.23
  name: diracx-cms-cli
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: diracx-cms-cli
      app.kubernetes.io/name: diracx-cli
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: diracx-cms-cli
        app.kubernetes.io/name: diracx-cli
    spec:
      containers:
      - args:
        - sleep
        - '2592000'
        command:
        - bash
        - /entrypoint.sh
        env:
        - name: DIRACX_URL
          value: https://cms-diracx-test18.cern.ch:8000
        - name: DIRACX_CA_PATH
          value: /ca/demo-ca.pem
        image: ghcr.io/diracgrid/diracx/client:v0.0.13
        imagePullPolicy: Always
        name: diracx-cli
        resources: {}
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /cs_store
          name: cs-store-mount
        - mountPath: /ca
          name: ca-mount
        - mountPath: /entrypoint.sh
          name: container-entrypoint
          subPath: entrypoint.sh
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: diracx-cms
      serviceAccountName: diracx-cms
      terminationGracePeriodSeconds: 30
      volumes:
      - name: cs-store-mount
        persistentVolumeClaim:
          claimName: pvc-cs-store
      - configMap:
          defaultMode: 420
          name: diracx-container-entrypoint
        name: container-entrypoint
      - name: ca-mount
        secret:
          defaultMode: 420
          items:
          - key: tls.crt
            path: demo-ca.pem
          secretName: root-secret
