apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: diracx-cms
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: diracx
    app.kubernetes.io/version: v0.0.13
    helm.sh/chart: diracx-1.0.23
  name: diracx-cms-cli
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: diracx-cms-cli
      app.kubernetes.io/name: diracx-cli
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: diracx-cms-cli
        app.kubernetes.io/name: diracx-cli
    spec:
      containers:
      - args:
        - sleep
        - '2592000'
        command:
        - bash
        - /entrypoint.sh
        env:
        - name: DIRACX_URL
          value: https://vkarm:8000
        - name: DIRACX_CA_PATH
          value: /ca/demo-ca.pem
        image: ghcr.io/diracgrid/diracx/client:v0.0.13
        imagePullPolicy: Always
        name: diracx-cli
        resources: {}
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /cs_store
          name: cs-store-mount
        - mountPath: /ca
          name: ca-mount
        - mountPath: /entrypoint.sh
          name: container-entrypoint
          subPath: entrypoint.sh
        - mountPath: /diracx_source
          name: diracx-code-mount
          readOnly: true
        - mountPath: /diracx_source/diracx/diracx-api/src/diracx_api.egg-info
          name: diracx-api-editable-install
        - mountPath: /diracx_source/diracx/diracx-tasks/src/diracx_tasks.egg-info
          name: diracx-tasks-editable-install
        - mountPath: /diracx_source/diracx/diracx-client/src/diracx_client.egg-info
          name: diracx-client-editable-install
        - mountPath: /diracx_source/diracx/diracx-db/src/diracx_db.egg-info
          name: diracx-db-editable-install
        - mountPath: /diracx_source/diracx/diracx-testing/src/diracx_testing.egg-info
          name: diracx-testing-editable-install
        - mountPath: /diracx_source/diracx/diracx-logic/src/diracx_logic.egg-info
          name: diracx-logic-editable-install
        - mountPath: /diracx_source/diracx/diracx-core/src/diracx_core.egg-info
          name: diracx-core-editable-install
        - mountPath: /diracx_source/diracx/diracx-cli/src/diracx_cli.egg-info
          name: diracx-cli-editable-install
        - mountPath: /diracx_source/diracx/diracx-routers/src/diracx_routers.egg-info
          name: diracx-routers-editable-install
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: diracx-cms
      serviceAccountName: diracx-cms
      terminationGracePeriodSeconds: 30
      volumes:
      - name: cs-store-mount
        persistentVolumeClaim:
          claimName: pvc-cs-store
      - name: diracx-code-mount
        persistentVolumeClaim:
          claimName: pvc-diracx-code
      - emptyDir:
          sizeLimit: 5Mi
        name: diracx-api-editable-install
      - emptyDir:
          sizeLimit: 5Mi
        name: diracx-tasks-editable-install
      - emptyDir:
          sizeLimit: 5Mi
        name: diracx-client-editable-install
      - emptyDir:
          sizeLimit: 5Mi
        name: diracx-db-editable-install
      - emptyDir:
          sizeLimit: 5Mi
        name: diracx-testing-editable-install
      - emptyDir:
          sizeLimit: 5Mi
        name: diracx-logic-editable-install
      - emptyDir:
          sizeLimit: 5Mi
        name: diracx-core-editable-install
      - emptyDir:
          sizeLimit: 5Mi
        name: diracx-cli-editable-install
      - emptyDir:
          sizeLimit: 5Mi
        name: diracx-routers-editable-install
      - configMap:
          defaultMode: 420
          name: diracx-container-entrypoint
        name: container-entrypoint
      - name: ca-mount
        secret:
          defaultMode: 420
          items:
          - key: tls.crt
            path: demo-ca.pem
          secretName: root-secret
