apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: diracx-cms
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mysql
    helm.sh/chart: mysql-9.11.0
  name: diracx-cms-mysql
  namespace: default
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: primary
      app.kubernetes.io/instance: diracx-cms
      app.kubernetes.io/name: mysql
  serviceName: diracx-cms-mysql
  template:
    metadata:
      labels:
        app.kubernetes.io/component: primary
        app.kubernetes.io/instance: diracx-cms
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: mysql
        helm.sh/chart: mysql-9.11.0
    spec:
      serviceAccountName: diracx-cms-mysql
      securityContext:
        fsGroup: 1001
      initContainers:
      - name: volume-permissions
        image: busybox
        command:
          - sh
          - -c
          - |
            cp /configmap/my.cnf /etc/mysql/my.cnf
            chmod 644 /etc/mysql/my.cnf
            chown 1001:1001 /etc/mysql/my.cnf
            chown -R 1001:1001 /bitnami/mysql
        volumeMounts:
        - name: data
          mountPath: /bitnami/mysql
        - name: config-source
          mountPath: /configmap
        - name: config-writable
          mountPath: /etc/mysql
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/instance: diracx-cms
                  app.kubernetes.io/name: mysql
              topologyKey: kubernetes.io/hostname
            weight: 1
      containers:
      - name: mysql
        image: docker.io/bitnamilegacy/mysql:8.0.34-debian-11-r8
        imagePullPolicy: IfNotPresent
        env:
        - name: BITNAMI_DEBUG
          value: 'false'
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mysql-root-password
              name: mysql-secret
        - name: MYSQL_USER
          value: sqldiracx
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mysql-password
              name: mysql-secret
        ports:
        - containerPort: 3306
          name: mysql
          protocol: TCP
        startupProbe:
          tcpSocket:
            port: mysql
          failureThreshold: 60
          periodSeconds: 5
          initialDelaySeconds: 10
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -ec
            - "mysqladmin ping -h 127.0.0.1 -uroot -p\"${MYSQL_ROOT_PASSWORD}\"\n"
          failureThreshold: 6
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -ec
            - "mysqladmin ping -h 127.0.0.1 -uroot -p\"${MYSQL_ROOT_PASSWORD}\"\n"
          failureThreshold: 30
          initialDelaySeconds: 30
          periodSeconds: 10
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
        volumeMounts:
        - mountPath: /bitnami/mysql
          name: data
        - mountPath: /docker-entrypoint-initdb.d
          name: custom-init-scripts
        - mountPath: /opt/bitnami/mysql/conf/my.cnf
          name: config-writable
          subPath: my.cnf
      volumes:
      - name: config-source
        configMap:
          name: diracx-cms-mysql  # Source ConfigMap (Read-only)
      - name: config-writable
        emptyDir: {}              # Writable space for the initContainer to copy into
      - name: custom-init-scripts
        configMap:
          name: mysql-init-diracx-dbs
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 8Gi
      volumeMode: Filesystem
