apiVersion: v1
data:
  create-issuer: "#!/bin/bash\nset -e ;\n\nissuer_file=$1\nnamespace=default\n\necho\
    \ \"Creating the certmanager issuer...\"\nset +e ; # The CRD may not exist yet.\
    \ We need to retry until this passes\nwhile ! kubectl --namespace=$namespace apply\
    \ -f ${issuer_file:=issuer.yml}; do\n  sleep 1;\ndone ;\nset -e ; # reset `e`\
    \ as active\n"
  issuer.yml: "\n---\napiVersion: cert-manager.io/v1\nkind: Issuer\nmetadata:\n  name:\
    \ selfsigned-issuer\nspec:\n  selfSigned: {}\n---\napiVersion: cert-manager.io/v1\n\
    kind: Certificate\nmetadata:\n  name: diracx-selfsigned-ca\nspec:\n  isCA: true\n\
    \  commonName: diracx-selfsigned-ca\n  secretName: root-secret\n  privateKey:\n\
    \    algorithm: ECDSA\n    size: 256\n  issuerRef:\n    name: selfsigned-issuer\n\
    \    kind: Issuer\n    group: cert-manager.io\n---\napiVersion: cert-manager.io/v1\n\
    kind: Issuer\nmetadata:\n  name: diracx-ca-issuer\nspec:\n  ca:\n    secretName:\
    \ root-secret\n"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
  name: diracx-cms-cert-manager-issuer-certmanager
  namespace: default
