apiVersion: v1
data:
  entrypoint.sh: "#!/bin/bash\nset -euo pipefail\nIFS=$'\\n\\t'\n\nulimit -n 8192\n\
    if [ -f \"/activate.sh\" ]; then\n  source /activate.sh\nelse\n  eval \"$(micromamba\
    \ shell hook --shell=posix)\" && micromamba activate base\nfi\n\nexec \"$@\"\n"
kind: ConfigMap
metadata:
  name: diracx-container-entrypoint
  namespace: default
