apiVersion: v1
data:
  cleanup-authdb: '#!/usr/bin/env bash

    set -euo pipefail

    IFS=$''\n\t''


    python -m diracx.logic cleanup-authdb

    '
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
  name: diracx-cms-cleanup-authdb
  namespace: default
