apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace }}
  labels:
    name: {{ .Values.global.namespace }}
    cert-manager.io/disable-validation: "true"
    {{ include "diracx-cms.labels" . | nindent 4 }}
