{{- $name := include "diracx-cms.name" . }}
{{- range .Values.serviceAccounts }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ . }}
  namespace: {{ $.Values.global.namespace }}
  labels:
    {{ include "diracx-cms.labels" $ | nindent 4 }}
{{- end }}
---
# Dedicated SA for init-secrets job (needs secret create/patch RBAC)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}-init-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    {{ include "diracx-cms.labels" . | nindent 4 }}
