{{- if .Values.taskWorkers.enabled }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "diracx.taskSchedulerName" . }}
  labels:
    {{- include "diracx.labels" . | nindent 4 }}
    app.kubernetes.io/component: task-scheduler
    app.kubernetes.io/part-of: diracx-tasks
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "diracxTaskScheduler.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        checksum/settings: {{ include (print $.Template.BasePath "/diracx/secrets.yaml") . | sha256sum }}
        checksum/init-settings: {{ include (print $.Template.BasePath "/diracx/init-secrets/configmap.yaml") . | sha256sum }}
        checksum/entrypoint: {{ include (print $.Template.BasePath "/diracx/diracx-container-entrypoint.yaml") . | sha256sum }}
      labels:
        {{- include "diracxTaskScheduler.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: task-scheduler
        app.kubernetes.io/part-of: diracx-tasks
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "diracx.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: cs-store-mount
          persistentVolumeClaim:
            claimName: pvc-cs-store
        - name: diracx-src
          persistentVolumeClaim:
            claimName: pvc-diracx-code
        {{- if and .Values.developer.enabled .Values.developer.mountedPythonModulesToInstall }}
        - name: diracx-code-mount
          persistentVolumeClaim:
            claimName: pvc-diracx-code
        {{- range $module := .Values.developer.mountedPythonModulesToInstall }}
        - name: {{ base $module | lower }}-editable-install
          emptyDir:
            sizeLimit: 5Mi
        {{- end }}
        {{- end }}
        - name: container-entrypoint
          configMap:
            name: diracx-container-entrypoint
        - name: jwks-mount
          secret:
            secretName: diracx-jwks
            items:
            - key: jwks.json
              path: jwks.json
      initContainers:
        - name: wait-for-diracx
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c', 'until nc -vz {{ include "diracx.fullname" . }} {{ .Values.diracx.service.port }}; do echo "Waiting for diracx..."; sleep 3; done;']
        {{- if .Values.redisTasks.enabled }}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}-task-scheduler
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.images.tasks }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          command: [ "/usr/local/bin/_entrypoint.sh", "tini", "--", "bash", "/entrypoint.sh" ]
          args:
            - diracx-task-run
            - scheduler
          volumeMounts:
            - name: cs-store-mount
              mountPath: /cs_store
            - name: container-entrypoint
              mountPath: /entrypoint.sh
              subPath: entrypoint.sh
            - name: jwks-mount
              mountPath: /keystore
            - name: diracx-src
              mountPath: /src
          env:
            - name: PYTHONPATH
              value: {{ $.Values.taskWorkers.pythonPath | quote }}
            - name: DIRACX_TASKS_CONDOR_JOB_EXECUTOR_ENABLED
              value: {{ if hasKey $.Values.taskWorkers "condorJobExecutorEnabled" }}{{ $.Values.taskWorkers.condorJobExecutorEnabled | quote }}{{ else }}"true"{{ end }}
          envFrom:
            - secretRef:
                name: diracx-secrets
            - secretRef:
                name: diracx-dynamic-secrets
            {{- if .Values.diracx.sqlDbs }}
            - secretRef:
                name: diracx-sql-connection-urls
            {{- end }}
            {{- if .Values.diracx.osDbs }}
            - secretRef:
                name: diracx-os-connection-urls
            {{- end }}
            - secretRef:
                name: diracx-task-redis-url
          resources:
            {{- toYaml (.Values.taskWorkers.scheduler.resources | default .Values.resources | default dict) | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
