---
apiVersion: v1
kind: ConfigMap
metadata:
  name: diracx-cms-init-cs
  namespace: default
data:
  init-cs: |
    #!/usr/bin/env bash
    set -euo pipefail

    # 1. Activate the environment
    source /activate.sh

    # 2. Add diracx code from PVC to PYTHONPATH
    export PYTHONPATH=${PYTHONPATH:-}:/src/diracx-logic/src:/src/diracx-core/src

    # Optional debug (very useful)
    echo "PYTHONPATH=$PYTHONPATH"
    ls -l /src || true

    # 3. Initialize the Configuration Service
    echo "Initializing Configuration Service in /cs_store..."

    dirac internal generate-cs /cs_store/initialRepo

    echo "CS initialization complete."

---
apiVersion: batch/v1
kind: Job
metadata:
  name: diracx-cms-init-cs
  namespace: default
spec:
  ttlSecondsAfterFinished: 3600
  activeDeadlineSeconds: 900
  backoffLimit: 6
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: diracx
          image: ghcr.io/diracgrid/diracx/client:v0.0.13
          imagePullPolicy: Always
          command: ["/bin/bash", "/entrypoint.sh"]
          args: ["/bin/bash", "/scripts/init-cs"]

          volumeMounts:
            - name: cs-store-mount
              mountPath: /cs_store

            - name: container-entrypoint
              mountPath: /entrypoint.sh
              subPath: entrypoint.sh

            - name: scripts
              mountPath: /scripts

            - name: diracx-src
              mountPath: /src

      volumes:
        - name: scripts
          configMap:
            name: diracx-cms-init-cs
            defaultMode: 0755

        - name: cs-store-mount
          persistentVolumeClaim:
            claimName: pvc-cs-store

        - name: container-entrypoint
          configMap:
            name: diracx-container-entrypoint
            defaultMode: 0755

        - name: diracx-src
          persistentVolumeClaim:
            claimName: pvc-diracx-code
