apiVersion: batch/v1
kind: Job
metadata:
  labels: {}
  name: diracx-cms-init-sql
  namespace: default
spec:
  activeDeadlineSeconds: 900
  backoffLimit: 6
  completionMode: NonIndexed
  completions: 1
  manualSelector: false
  parallelism: 1
  podReplacementPolicy: TerminatingOrFailed
  suspend: false
  template:
    spec:
      containers:
      - args:
        - /bin/bash
        - /scripts/init-sql
        command:
        - /bin/bash
        - /entrypoint.sh
        env:
        - name: DIRACX_DB_URL_AUTHDB
          valueFrom:
            secretKeyRef:
              key: DIRACX_DB_URL_AUTHDB
              name: diracx-sql-root-connection-urls
        - name: DIRACX_DB_URL_JOBDB
          valueFrom:
            secretKeyRef:
              key: DIRACX_DB_URL_JOBDB
              name: diracx-sql-root-connection-urls
        - name: DIRACX_DB_URL_JOBLOGGINGDB
          valueFrom:
            secretKeyRef:
              key: DIRACX_DB_URL_JOBLOGGINGDB
              name: diracx-sql-root-connection-urls
        - name: DIRACX_DB_URL_PILOTAGENTSDB
          valueFrom:
            secretKeyRef:
              key: DIRACX_DB_URL_PILOTAGENTSDB
              name: diracx-sql-root-connection-urls
        - name: DIRACX_DB_URL_SANDBOXMETADATADB
          valueFrom:
            secretKeyRef:
              key: DIRACX_DB_URL_SANDBOXMETADATADB
              name: diracx-sql-root-connection-urls
        - name: DIRACX_DB_URL_TASKQUEUEDB
          valueFrom:
            secretKeyRef:
              key: DIRACX_DB_URL_TASKQUEUEDB
              name: diracx-sql-root-connection-urls
        image: ghcr.io/diracgrid/diracx/services:v0.0.13
        imagePullPolicy: Always
        name: diracx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /entrypoint.sh
          name: container-entrypoint
          subPath: entrypoint.sh
        - mountPath: /diracx_source
          name: diracx-code-mount
          readOnly: true
        - mountPath: /diracx_source/diracx/diracx-api/src/diracx_api.egg-info
          name: diracx-api-editable-install
        - mountPath: /diracx_source/diracx/diracx-tasks/src/diracx_tasks.egg-info
          name: diracx-tasks-editable-install
        - mountPath: /diracx_source/diracx/diracx-client/src/diracx_client.egg-info
          name: diracx-client-editable-install
        - mountPath: /diracx_source/diracx/diracx-db/src/diracx_db.egg-info
          name: diracx-db-editable-install
        - mountPath: /diracx_source/diracx/diracx-testing/src/diracx_testing.egg-info
          name: diracx-testing-editable-install
        - mountPath: /diracx_source/diracx/diracx-logic/src/diracx_logic.egg-info
          name: diracx-logic-editable-install
        - mountPath: /diracx_source/diracx/diracx-core/src/diracx_core.egg-info
          name: diracx-core-editable-install
        - mountPath: /diracx_source/diracx/diracx-cli/src/diracx_cli.egg-info
          name: diracx-cli-editable-install
        - mountPath: /diracx_source/diracx/diracx-routers/src/diracx_routers.egg-info
          name: diracx-routers-editable-install
        - mountPath: /scripts
          name: scripts
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - sh
        - -c
        - until nc -vz diracx-cms-mysql 3306; do echo "Waiting for mysql..."; sleep
          3; done;
        image: docker.io/library/busybox:latest
        imagePullPolicy: IfNotPresent
        name: wait-for-mysql
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: diracx-cms-init-sql
        name: scripts
      - name: diracx-code-mount
        persistentVolumeClaim:
          claimName: pvc-diracx-code
      - emptyDir:
          sizeLimit: 5Mi
        name: diracx-api-editable-install
      - emptyDir:
          sizeLimit: 5Mi
        name: diracx-tasks-editable-install
      - emptyDir:
          sizeLimit: 5Mi
        name: diracx-client-editable-install
      - emptyDir:
          sizeLimit: 5Mi
        name: diracx-db-editable-install
      - emptyDir:
          sizeLimit: 5Mi
        name: diracx-testing-editable-install
      - emptyDir:
          sizeLimit: 5Mi
        name: diracx-logic-editable-install
      - emptyDir:
          sizeLimit: 5Mi
        name: diracx-core-editable-install
      - emptyDir:
          sizeLimit: 5Mi
        name: diracx-cli-editable-install
      - emptyDir:
          sizeLimit: 5Mi
        name: diracx-routers-editable-install
      - configMap:
          defaultMode: 420
          name: diracx-container-entrypoint
        name: container-entrypoint
  ttlSecondsAfterFinished: 3600
