apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
  name: diracx-cms-issuer-1
  namespace: default
spec:
  activeDeadlineSeconds: 300
  backoffLimit: 6
  completionMode: NonIndexed
  completions: 1
  manualSelector: false
  parallelism: 1
  podReplacementPolicy: TerminatingOrFailed
  selector:
    matchLabels:
      batch.kubernetes.io/controller-uid: 4c8d08fe-a97a-433d-87d3-c091f38f7ec0
  suspend: false
  template:
    metadata:
      labels:
        app: cert-manager-issuer
        batch.kubernetes.io/controller-uid: 4c8d08fe-a97a-433d-87d3-c091f38f7ec0
        batch.kubernetes.io/job-name: diracx-cms-issuer-1
        controller-uid: 4c8d08fe-a97a-433d-87d3-c091f38f7ec0
        job-name: diracx-cms-issuer-1
        release: diracx-cms
    spec:
      containers:
      - command:
        - /bin/bash
        - /scripts/create-issuer
        - /scripts/issuer.yml
        image: ghcr.io/diracgrid/diracx/secret-generation:latest
        imagePullPolicy: Always
        name: create-issuer
        resources:
          requests:
            cpu: 50m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /scripts
          name: scripts
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: diracx-cms-cert-manager-issuer
      serviceAccountName: diracx-cms-cert-manager-issuer
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: diracx-cms-cert-manager-issuer-certmanager
        name: scripts
  ttlSecondsAfterFinished: 3600
