apiVersion: batch/v1
kind: Job
metadata:
  labels: {}
  name: diracx-cms-init-secrets
  namespace: default
spec:
  activeDeadlineSeconds: 900
  backoffLimit: 6
  completionMode: NonIndexed
  completions: 1
  manualSelector: false
  parallelism: 1
  podReplacementPolicy: TerminatingOrFailed
  selector:
    matchLabels:
      batch.kubernetes.io/controller-uid: 4109bdce-3dcb-4c3c-b05d-fbde548f786e
  suspend: false
  template:
    metadata:
      labels:
        batch.kubernetes.io/controller-uid: 4109bdce-3dcb-4c3c-b05d-fbde548f786e
        batch.kubernetes.io/job-name: diracx-cms-init-secrets-1-lgu
        controller-uid: 4109bdce-3dcb-4c3c-b05d-fbde548f786e
        job-name: diracx-cms-init-secrets-1-lgu
    spec:
      containers:
      - args:
        - /bin/bash
        - /scripts/init-secrets
        image: ghcr.io/diracgrid/diracx/secret-generation:latest
        imagePullPolicy: Always
        name: diracx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /scripts
          name: scripts
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: diracx-cms-init-secrets
      serviceAccountName: diracx-cms-init-secrets
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: diracx-cms-init-secrets
        name: scripts
  ttlSecondsAfterFinished: 3600
