---
apiVersion: v1
kind: ConfigMap
metadata:
  name: diracx-cms-init-keystore
  namespace: default
data:
  init-keystore: |
    #!/usr/bin/env bash
    set -euo pipefail
    source /activate.sh

    # POINT PYTHON TO THE MOUNTED SOURCE
    export PYTHONPATH=$PYTHONPATH:/src/diracx-logic/src:/src/diracx-core/src

    mkdir -p /keystore
    KEYSTORE_PATH=/keystore/jwks.json

    if [[ -f $KEYSTORE_PATH ]]; then
        echo "JWKS already exists, skipping."
        exit 0
    fi

    python -m diracx.logic rotate-jwk --jwks-path $KEYSTORE_PATH

  load-keystore-as-secret: |
    #!/usr/bin/env bash
    set -euo pipefail

    KEYSTORE_PATH=/keystore/jwks.json

    if kubectl get secret diracx-jwks >/dev/null 2>&1; then
      echo "diracx-jwks already present, skipping."
      exit 0
    fi

    kubectl create secret generic diracx-jwks --from-file=jwks.json=$KEYSTORE_PATH

---
apiVersion: batch/v1
kind: Job
metadata:
  name: diracx-cms-init-keystore
  namespace: default
spec:
  backoffLimit: 3
  template:
    spec:
      serviceAccountName: diracx-cms-init-secrets
      restartPolicy: Never

      initContainers:
        - name: diracx-init-keystore
          image: ghcr.io/diracgrid/diracx/services:v0.0.13
          command: ["/bin/bash", "/entrypoint.sh"]
          args: ["/bin/bash", "/scripts/init-keystore"]

          volumeMounts:
            - name: container-entrypoint
              mountPath: /entrypoint.sh
              subPath: entrypoint.sh

            - name: scripts
              mountPath: /scripts

            - name: keystore
              mountPath: /keystore

            - name: diracx-src
              mountPath: /src

      containers:
        - name: diracx-load-keystore-as-secret
          image: ghcr.io/diracgrid/diracx/secret-generation:latest
          command: ["/bin/bash", "/scripts/load-keystore-as-secret"]

          volumeMounts:
            - name: scripts
              mountPath: /scripts

            - name: keystore
              mountPath: /keystore

            - name: diracx-src
              mountPath: /src

      volumes:
        - name: keystore
          emptyDir: {}

        - name: scripts
          configMap:
            name: diracx-cms-init-keystore
            defaultMode: 0755

        - name: container-entrypoint
          configMap:
            name: diracx-container-entrypoint
            defaultMode: 0755

        - name: diracx-src
          persistentVolumeClaim:
            claimName: pvc-diracx-code
