apiVersion: batch/v1
kind: Job
metadata:
  name: diracx-cms-init-cs
  namespace: default
spec:
  activeDeadlineSeconds: 900
  backoffLimit: 6
  completionMode: NonIndexed
  completions: 1
  manualSelector: false
  parallelism: 1
  podReplacementPolicy: TerminatingOrFailed
  suspend: false
  template:
    metadata:
      labels: {}
    spec:
      containers:
      - args:
        - /bin/bash
        - /scripts/init-cs
        command:
        - /bin/bash
        - /entrypoint.sh
        image: ghcr.io/diracgrid/diracx/client:v0.0.13
        imagePullPolicy: Always
        name: diracx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /cs_store
          name: cs-store-mount
        - mountPath: /entrypoint.sh
          name: container-entrypoint
          subPath: entrypoint.sh
        - mountPath: /scripts
          name: scripts
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: diracx-cms-init-cs
        name: scripts
      - name: cs-store-mount
        persistentVolumeClaim:
          claimName: pvc-cs-store
      - configMap:
          defaultMode: 420
          name: diracx-container-entrypoint
        name: container-entrypoint
  ttlSecondsAfterFinished: 3600
