apiVersion: batch/v1
kind: Job
metadata:
  labels: {}
  name: diracx-cms-init-keystore
  namespace: default
spec:
  activeDeadlineSeconds: 900
  backoffLimit: 6
  completionMode: NonIndexed
  completions: 1
  manualSelector: false
  parallelism: 1
  podReplacementPolicy: TerminatingOrFailed
  selector:
    matchLabels:
      batch.kubernetes.io/controller-uid: 0aade14a-1f0c-4e8e-8aca-a5951fe1a9ff
  suspend: false
  template:
    metadata:
      labels:
        batch.kubernetes.io/controller-uid: 0aade14a-1f0c-4e8e-8aca-a5951fe1a9ff
        batch.kubernetes.io/job-name: diracx-cms-init-keystore-1-m73
        controller-uid: 0aade14a-1f0c-4e8e-8aca-a5951fe1a9ff
        job-name: diracx-cms-init-keystore-1-m73
    spec:
      containers:
      - args:
        - /bin/bash
        - /scripts/load-keystore-as-secret
        image: ghcr.io/diracgrid/diracx/secret-generation:latest
        imagePullPolicy: Always
        name: diracx-load-keystore-as-secret
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /scripts
          name: scripts
        - mountPath: /keystore
          name: keystore
      dnsPolicy: ClusterFirst
      initContainers:
      - args:
        - /bin/bash
        - /scripts/init-keystore
        command:
        - /bin/bash
        - /entrypoint.sh
        image: ghcr.io/diracgrid/diracx/services:v0.0.13
        imagePullPolicy: Always
        name: diracx-init-keystore
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /entrypoint.sh
          name: container-entrypoint
          subPath: entrypoint.sh
        - mountPath: /diracx_source
          name: diracx-code-mount
          readOnly: true
        - mountPath: /diracx_source/diracx/diracx-api/src/diracx_api.egg-info
          name: diracx-api-editable-install
        - mountPath: /diracx_source/diracx/diracx-tasks/src/diracx_tasks.egg-info
          name: diracx-tasks-editable-install
        - mountPath: /diracx_source/diracx/diracx-client/src/diracx_client.egg-info
          name: diracx-client-editable-install
        - mountPath: /diracx_source/diracx/diracx-db/src/diracx_db.egg-info
          name: diracx-db-editable-install
        - mountPath: /diracx_source/diracx/diracx-testing/src/diracx_testing.egg-info
          name: diracx-testing-editable-install
        - mountPath: /diracx_source/diracx/diracx-logic/src/diracx_logic.egg-info
          name: diracx-logic-editable-install
        - mountPath: /diracx_source/diracx/diracx-core/src/diracx_core.egg-info
          name: diracx-core-editable-install
        - mountPath: /diracx_source/diracx/diracx-cli/src/diracx_cli.egg-info
          name: diracx-cli-editable-install
        - mountPath: /diracx_source/diracx/diracx-routers/src/diracx_routers.egg-info
          name: diracx-routers-editable-install
        - mountPath: /scripts
          name: scripts
        - mountPath: /keystore
          name: keystore
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: diracx-cms-init-secrets
      serviceAccountName: diracx-cms-init-secrets
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: keystore
      - configMap:
          defaultMode: 420
          name: diracx-cms-init-keystore
        name: scripts
      - name: diracx-code-mount
        persistentVolumeClaim:
          claimName: pvc-diracx-code
      - emptyDir:
          sizeLimit: 5Mi
        name: diracx-api-editable-install
      - emptyDir:
          sizeLimit: 5Mi
        name: diracx-tasks-editable-install
      - emptyDir:
          sizeLimit: 5Mi
        name: diracx-client-editable-install
      - emptyDir:
          sizeLimit: 5Mi
        name: diracx-db-editable-install
      - emptyDir:
          sizeLimit: 5Mi
        name: diracx-testing-editable-install
      - emptyDir:
          sizeLimit: 5Mi
        name: diracx-logic-editable-install
      - emptyDir:
          sizeLimit: 5Mi
        name: diracx-core-editable-install
      - emptyDir:
          sizeLimit: 5Mi
        name: diracx-cli-editable-install
      - emptyDir:
          sizeLimit: 5Mi
        name: diracx-routers-editable-install
      - configMap:
          defaultMode: 420
          name: diracx-container-entrypoint
        name: container-entrypoint
  ttlSecondsAfterFinished: 3600
