---
# MutatingWebhookConfiguration for cert-manager v1.13.1
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: diracx-cms-cert-manager-webhook
  labels:
    app: webhook
    app.kubernetes.io/component: webhook
    app.kubernetes.io/instance: diracx-cms
    app.kubernetes.io/name: webhook
    app.kubernetes.io/version: v1.13.1
  annotations:
    cert-manager.io/inject-ca-from-secret: "default/diracx-cms-cert-manager-webhook-ca"
webhooks:
  - name: webhook.cert-manager.io
    admissionReviewVersions: ["v1"]
    clientConfig:
      service:
        name: diracx-cms-cert-manager-webhook
        namespace: default
        path: /mutate
        port: 443
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ3akNDQVVpZ0F3SUJBZ0lSQU1yeW9oU1laTlFMdGl4S0toSTB2RzR3Q2dZSUtvWkl6ajBFQXdNd0lqRWcKTUI0R0ExVUVBeE1YWTJWeWRDMXRZVzVoWjJWeUxYZGxZbWh2YjJzdFkyRXdIaGNOTWpZd05ESTRNVE0wT0RBegpXaGNOTWpjd05ESTRNVE0wT0RBeldqQWlNU0F3SGdZRFZRUURFeGRqWlhKMExXMWhibUZuWlhJdGQyVmlhRzl2CmF5MWpZVEIyTUJBR0J5cUdTTTQ5QWdFR0JTdUJCQUFpQTJJQUJLM3Irandsc1h1TzRQYmxSNnJhcTRKUmpvU0EKVjNpbHN2OVBRMDhVQk1Bd2ZSUEZqc1VOUGR3TTZ1ZnNHRGtlMGlFbTZKOEtRendLZnk4WFFuWFJJb2IrZnhFWApGSEoxeW0zRmxaeTdUTEtZQmwwb3AvNEhCSWVRWnJOZm9yVE5mNk5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trCk1BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZDN2hwc2c0Y1kvcDAycmwvaDk5OVF6eU1qclMKTUFvR0NDcUdTTTQ5QkFNREEyZ0FNR1VDTVFEMFFvbnBFNGExTytkZkpzYjk3YjlsN3BhaTNkMFdoa3lQN0pRWApLY1RCdmtmM2lzRjFXOXdJeHBwb1JqQlcveE1DTURPeEpUdWVuUFYxSHl0elhtczg1bEVZWjlsM2oxKzcrV1ErCjQzVGRBL1lIMDJsUXhvbkhvSWl0NWJmZkIyaVl1UT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
    failurePolicy: Ignore
    matchPolicy: Equivalent
    namespaceSelector:
      matchExpressions:
        - key: "cert-manager.io/disable-validation"
          operator: NotIn
          values: ["true"]
        - key: "kubernetes.io/metadata.name"
          operator: NotIn
          values: ["kube-system"]
    rules:
      - apiGroups:   ["cert-manager.io", "acme.cert-manager.io"]
        apiVersions: ["v1"]
        operations:  ["CREATE", "UPDATE"]
        resources:   ["*/*"]
    sideEffects: None
    timeoutSeconds: 30
