apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: cert-manager-issuer
    app.kubernetes.io/managed-by: Helm
    chart: cert-manager-issuer-0.0.1
    heritage: Helm
    release: diracx-cms
  name: diracx-cms-cert-manager-issuer
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: diracx-cms-cert-manager-issuer
subjects:
- kind: ServiceAccount
  name: diracx-cms-cert-manager-issuer
  namespace: default
