apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: diracx-cms
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: dex
    app.kubernetes.io/version: 2.36.0
    helm.sh/chart: dex-0.14.2
  name: diracx-cms-dex
  namespace: default
