apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/instance: diracx-cms
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: diracx
    app.kubernetes.io/version: v0.0.13
    helm.sh/chart: diracx-1.0.23
  name: diracx-cms
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: cms-diracx-test18.cern.ch
    http:
      paths:
      - backend:
          service:
            name: diracx-cms
            port:
              number: 8000
        path: /api
        pathType: Prefix
      - backend:
          service:
            name: diracx-cms
            port:
              number: 8000
        path: /.well-known
        pathType: Prefix
      - backend:
          service:
            name: diracx-cms-web
            port:
              number: 8080
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - cms-diracx-test18.cern.ch
    secretName: myingress-cert
