apiVersion: v1
data:
  DIRACX_SERVICE_AUTH_STATE_KEY: VTdaMTJETWNoblVRejVyc3dNNGxjd2RzNGswblRabjBmQTRTK1BwUU9zRT0=
kind: Secret
metadata:
  name: diracx-dynamic-secrets
  namespace: default
type: Opaque
