apiVersion: v1
data:
  mysql-password: cm9WU1NnbE50WFNtRGlOc3h3c1pmUHpaTzVmRW5yM1c=
  mysql-replication-password: dlh6M0UxcE5GMzRudFU5cVp4YUZyR2pGNnJleWRwakQ=
  mysql-root-password: TXpsc3ZxUW4xQnRXYWM2M2FYRVRucWlNM3NSUmt5OEI=
kind: Secret
metadata:
  name: mysql-secret
  namespace: default
type: Opaque
